### ISSUE TITLE
spikegadgets reader inverts sign

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#102]
ndi_daqreader_mfdaq_spikegadgets appears to read "negative" signal rather than signal. The inversion might take place in the vhlab-thirdparty-matlab libraries. 

Which should be modified? I think we ought to correct it so it follows the native signal.

**Comment by danielgmu** [comment]
fixed in vhlab-toolbox-matlab commit 1ce99ea38befeb0a6b974f3c29d260b36fcaa6dc
