### ISSUE TITLE
Running a profile analysis on code block 2.4.5.1

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#183]
Running a profile analysis on code block 2.4.5.1 
`for i=1:2,
    tdoc{i} = oapp.calculate_tuning_curve(e{i});
    oriprops{i} = oapp.calculate_all_oridir_indexes(e{i}); 
end;`

is returning the following error:

> Warning: Matrix is singular to working precision. 
> In vlt.stats.hotellingt2test (line 27)
In vlt.neuro.vision.oridir.index.oridir_vectorindexes
(line 89)
In ndi.app/oridirtuning/calculate_oridir_indexes
(line 134)
In ndi.app/oridirtuning/calculate_all_oridir_indexes
(line 72)
 
Warning: Matrix is singular to working precision. 
> In vlt.stats.hotellingt2test (line 27)
In vlt.neuro.vision.oridir.index.oridir_vectorindexes
(line 96)
In ndi.app/oridirtuning/calculate_oridir_indexes
(line 134)
In ndi.app/oridirtuning/calculate_all_oridir_indexes
(line 72)
 
Warning: Matrix is singular to working precision. 
> In vlt.stats.hotellingt2test (line 27)
In vlt.neuro.vision.oridir.index.oridir_vectorindexes
(line 89)
In ndi.app/oridirtuning/calculate_oridir_indexes
(line 134)
In ndi.app/oridirtuning/calculate_all_oridir_indexes
(line 72)
 
Warning: Matrix is singular to working precision. 
> In vlt.stats.hotellingt2test (line 27)
In vlt.neuro.vision.oridir.index.oridir_vectorindexes
(line 96)
In ndi.app/oridirtuning/calculate_oridir_indexes
(line 134)
In ndi.app/oridirtuning/calculate_all_oridir_indexes
(line 72)
 
Warning: Matrix is singular to working precision. 
> In vlt.stats.hotellingt2test (line 27)
In vlt.neuro.vision.oridir.index.oridir_vectorindexes
(line 89)
In ndi.app/oridirtuning/calculate_oridir_indexes
(line 134)
In ndi.app/oridirtuning/calculate_all_oridir_indexes
(line 72)
 
Warning: Matrix is singular to working precision. 
> In vlt.stats.hotellingt2test (line 27)
In vlt.neuro.vision.oridir.index.oridir_vectorindexes
(line 96)
In ndi.app/oridirtuning/calculate_oridir_indexes
(line 134)
In ndi.app/oridirtuning/calculate_all_oridir_indexes
(line 72)

The figures appear as attached. 
![Screenshot 2021-06-06 014603](https://user-images.githubusercontent.com/83798182/120914029-52537900-c669-11eb-83a3-04b55c4022d3.png)

_Originally posted by @KellyZhangL in https://github.com/VH-Lab/NDI-matlab/issues/179#issuecomment-855343183_

**Comment by stevevanhooser** [comment]
Hi Kelly - 

Do I understand correctly that there seems to be some problem running this with the profiler? (That is, if you run it with the profiler off, it runs fine, but it returns an error when the profiler is being used?)

Thanks
Steve

**Comment by KellyZhangL** [comment]
I retried it this morning with `profile off` and I'm getting the same errors.

**Comment by stevevanhooser** [comment]
OK, is it possible that in the new run, you didn't select spikes for the cluster? It seems like the "neurons" don't have any activity in them.

**Comment by KellyZhangL** [comment]
That definitely is possible since I only assigned a quality label in the spike sorter app without doing anything else.

**Comment by KellyZhangL** [comment]
Issue solved! The error was me not selecting spikes for the clusters beforehand. I was wondering, if I selected different spike clusters, would my graphs in this code block look different?

**Comment by stevevanhooser** [comment]
Yes, in many cases. These recordings show very well isolated neurons; but, if there were multiple clusters and the neurons that they represented had different properties, then the results would differ.
