### ISSUE TITLE
re-imagine ndi.app.oridirtuning as ndi.calculations

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#200]
Hi Kelly - 

Want to take a stab at re-imagining ndi.app.oridirtuning as ndi.calculations?

I made a new branch "oridirtuning_as_calcs" for this purpose.

Best
Steve

**Comment by KellyZhangL** [comment]
Yes, I'll take a look and see what calculations I can create!

**Comment by stevevanhooser** [comment]
First calculation app: 

ndi.calc.vision.oridirtuning

Output document would be related to the existing oridirtuning document, except instead of "simple" we'd have:

    "oridirtuning": {
        "input_parameters": {
            "tuningdoc_id":                   []
        },
        "properties":                       (everything that the current oridirtuning document has)
        "tuning_curve":      (everything that the current oridirtuning document has)
        "significance":     (everything that the current oridirtuning document has)
        "vector":     (everything that the current oridirtuning document has)
       "fit"     (everything that the current oridirtuning document has)
     
    }
