### ISSUE TITLE
Error on ndi_install: "The program git was not detected on the system. Please install git and restart Matlab."

### ISSUE THREAD

**Issue by lakesare** [VH-Lab/NDI-matlab#227]
Git is installed on my system on mac (and works from the command line), and yet I get the **"The program git was not detected on the system. Please install git and restart Matlab."** error in Matlab terminal.

> <img width="704" alt="image" src="https://user-images.githubusercontent.com/7578559/177175817-254cb399-330e-4613-a40c-0cf0d58f130b.png">

**Comment by lakesare** [comment]
This is fixed by `xcode-select --install`.

Even if you have `git` installed locally, and it works from your terminal, you might still need to install git via `xcode-select --install` for Matlab's `system('git')` call to work.

**Comment by stevevanhooser** [comment]
Hi - what is the path to your installed GitHub? Matlab's underlying shell does not have the same path as the Apple Terminal and probably it was just missing from Matlab's path. We could add the path.

**Comment by lakesare** [comment]
Hi!
You're right, different PATHs in terminal (`echo $PATH`) VS in Matlab (`system('echo $PATH')`) on my system. 
My git was in `/usr/local/bin`, which was absent from Matlab's paths.

Then the general advise for this issue is to set PATH to your git location:
- via the system call (`system(['export PATH='YOUR_GIT_PATH' ; ' git'])` or `system(['set PATH='YOUR_GIT_PATH' && ' git'])`), depending on your OS
- via setting the path for all system calls ([https://www.mathworks.com/help/matlab/ref/path.html](https://www.mathworks.com/help/matlab/ref/path.html)).

We probably don't need to incorporate any changes into `ndi_install.m`, maybe just add some info to the error message, e.g. "We can't detect git on your system. Please install it, or make sure it's on Matlab's path (see all paths via `system('echo $PATH')`)."?
