### ISSUE TITLE
speed-up: write a listbinaryfiles(S, ndi_doc_obj) function

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#259]
Right now it is difficult to see which files, of the binary files allowed in the schema, are actually stored with an ndi.document object in a dataset or session.

It would speed up many operations if we could retrieve a list. Then one wouldn't have to try opening files and check for a failure.

**Comment by ehennestad** [comment]
This is what you had in mind?

**Comment by ehennestad** [comment]
Or would there be use cases for a function for doing this for individual dataset documents? The function I added lists files for all documents provided. You can of course pass a single document, but maybe better to create a function to do it for a single document, and then use that function in a loop when listing files for more documents.

**Comment by stevevanhooser** [comment]
Yes, this is perfect..then the other functions become smaller and easier to read and more robust. Thanks!
