### ISSUE TITLE
convert underlying object saving format to use ndi_document/ndi_database

### ISSUE THREAD

**Issue by stevevanhooser** [VH-Lab/NDI-matlab#83]
We developed our own conventions for platform-independent object saving. Well, JSON does that already and there are readers and writers for many languages. We should use that.

**Comment by stevevanhooser** [comment]
First step: writing newdocument and searchquery methods for ndi_filenavigator (basically, making ndi_filenavigator a subclass of ndi_documentservice)

**Comment by zhaoy17** [comment]
NDI_filenavigator, NDI_daqsystem's creator and newdocument() methods have been successfully tested.

**Comment by zhaoy17** [comment]
NDI_daqreader newdocument() method also works, but since NDI_daqreader() has no field and up to the subclass to implement, we weren't sure how to pass the ndi_document() as parameter to construct the NDI_daqreader()

**Comment by zhaoy17** [comment]
We also need the json file for ndi_syncrule in order for the syngraph newdocumet() method to work.

**Comment by zhaoy17** [comment]
There also seems to be some issue with experiment.database_rm in the experiment class, which we encounter error when trying to remove a cell of ndi_documents that has been added into the experiment either together or individually. 

Here is the error message


**Error using fieldsearch (line 144)
Unknown search operation hasanysubfield_exact_string

Error in dumbjsondb/ismatch (line 912)
					b = fieldsearch(struct(document),searchParams);

Error in dumbjsondb/search (line 418)
						b = dumbjsondb.ismatch(doc_here, searchParams);

Error in ndi_matlabdumbjsondb/do_search (line 85)
			[docs,doc_versions] = ndi_matlabdumbjsondb_obj.db.search(searchoptions,
                        searchparams);

Error in ndi_database/search (line 222)
				[ndi_document_objs, versions] =
                                ndi_database_obj.do_search(searchOptions,searchparams);

Error in ndi_experiment/database_search (line 266)
				ndi_document_obj =
                                ndi_experiment_obj.database.search(searchparameters);

Error in ndi_findalldependencies (line 27)
	bb = E.database_search(q_v);

Error in ndi_experiment/database_rm (line 241)
					dependent_docs =
                                        ndi_findalldependencies(ndi_experiment_obj,[],doc_unique_id{:});**

**Comment by stevevanhooser** [comment]
Hi Peter - Have you updated vhlab-toolbox-matlab to the latest? That was added within the last 4 months or so. There could still be an error, just curious if it is up-to-date. Thanks!

**Comment by zhaoy17** [comment]
We will try to check it!

**Comment by stevevanhooser** [comment]
OK, thanks guys. I edited this code a bit. You're right that the syncrule saving in syncgraph was tricky. I had to add a new feature to ndi_document to allow it to add a list of dependencies of a given type rather than just simply enumerated dependencies. This has been merged.

So, now, all of the core documents (ndi_daqsystem*, ndi_daqreader*, ndi_syncrule*, ndi_filenavigator*, and ndi_syncgraph) have the ability to generate ndi_documents and to be built by them.

I added a field to most document json files called ndi_[object]_class so that the object class can be stored. For example, in ndi_daqreader, I added, under daqreader, a field called ndi_daqreader_class. This allows the same ndi_document to be used for ndi_daqreader, ndi_daqreader_mfdaq, ndi_daqreader_mfdaq_intan, etc. 

In order to build objects this way, I had to add a new function called ndi_document2ndi_object. It examines the ndi_document and calls the right constructor to build the object. This is found in all of the test code.

A good test code example to read is test_ndi_daqreader_documents.m. It illustrates the whole flow.

Nice work guys, I used the bones of the code you made, with a few changes.

**Comment by stevevanhooser** [comment]
The next step is to create a branch that alters ndi_experiment so that it _uses_ the document versions in its calls to daqsystem_add, daqsystem_rm, daqsystem_clear, daqsystem_load, syncgraph_addrule, syncgraph_rmrule, findexpobj instead of the dbleaf list.

**Comment by stevevanhooser** [comment]
I've just made a new branch for this work called ndi_nodbleaf3

**Comment by stevevanhooser** [comment]
OK, I just looked at the code and made a small change. You can proceed to ndi_experiment.daqsystem_rm() and ndi_experiment.daqsystem_load()

Thanks!
Steve

**Comment by stevevanhooser** [comment]
ndi_noleaf3 updated..dbleaf and dbleafbranch have been removed and excised. Several small changes were necessary. All test code works. 

The next step is remove ndi_base so we are just left with ndi_id as the parent for all objects that currently are children of ndi_base.

Steve will do that tomorrow
